'use strict'
/**
 * setup.js — Treetop Management Server one-time setup helper
 *
 * Called by setup.bat AFTER npm install completes.  Safe to re-run — it will
 * never overwrite an existing .env or erase database data.
 *
 * What it does:
 *   1. Generates .env with a strong random JWT_SECRET  (skipped if .env exists)
 *   2. Initialises the database schema (CREATE TABLE IF NOT EXISTS — idempotent)
 *   3. Runs pending column-level migrations
 */

const fs     = require('fs')
const path   = require('path')
const crypto = require('crypto')

const ROOT    = __dirname
const envPath = path.join(ROOT, '.env')

// ── Step 1: .env ─────────────────────────────────────────────────────────────

if (fs.existsSync(envPath)) {
  console.log('  [env]  .env already exists — keeping existing JWT_SECRET.')
} else {
  // 48 random bytes → 96-char hex string.  Far beyond any brute-force threshold.
  const secret  = crypto.randomBytes(48).toString('hex')
  const content = [
    '# Treetop Management Server — generated by setup.bat',
    '# DO NOT share or commit this file.',
    '',
    `JWT_SECRET=${secret}`,
    'PORT=3001',
    'NODE_ENV=production',
    '',
  ].join('\n')
  fs.writeFileSync(envPath, content, 'utf8')
  console.log('  [env]  .env created with a fresh 96-char JWT_SECRET.')
}

// Load the .env we just created/verified so any downstream require that reads
// process.env (e.g. database.js path resolution) gets the right values.
require('dotenv').config({ path: envPath })

// ── Step 2: Database schema ───────────────────────────────────────────────────
// initializeDatabase uses CREATE TABLE IF NOT EXISTS — completely safe to re-run
// on an existing deployment.  We do NOT call seed.js because that inserts demo
// users.  A production deployment starts with an empty database and goes through
// the bootstrap-token flow on first launch.

try {
  const { initializeDatabase } = require('./db/schema')
  initializeDatabase()
  console.log('  [db]   Schema initialised (tables created if they did not exist).')
} catch (err) {
  console.error('\n  [db]   ERROR: Schema initialisation failed.')
  console.error('         ' + err.message)
  process.exit(1)
}

// ── Step 3: Migrations ────────────────────────────────────────────────────────
// Applies any ALTER TABLE changes that were added after initial release.

try {
  const { migrate } = require('./db/migrate')
  migrate()
  console.log('  [db]   Migrations applied.')
} catch (err) {
  console.error('\n  [db]   ERROR: Migration failed.')
  console.error('         ' + err.message)
  process.exit(1)
}

console.log('\n  Setup finished successfully.')
console.log('  Start the server by double-clicking start-treetop-server.bat\n')
